### ISSUE TITLE
update-winget task is changing multiple files with PRs into winget-pkgs

### ISSUE THREAD

**Issue by ldennington** [mjcheetham/update-winget#105]
There is a bug in the `update-winget` task that is making it open PRs against the winget-pkgs repo with multiple manifest files (there should only ever be one updated file per Pull Request).

This looks to be failing in [this line](https://github.com/mjcheetham/update-winget/blob/247c81a7d8bcf7d81b9a2df3788aaf0bfb200e73/src/winget.ts#L78) of [this if block](https://github.com/mjcheetham/update-winget/blob/247c81a7d8bcf7d81b9a2df3788aaf0bfb200e73/src/winget.ts#L55-L61).

**Comment by dscho** [comment]
Is this fixed by #107?

**Comment by mjcheetham** [comment]
I believe it is fixed by #107

**Comment by ldennington** [comment]
Yep! It was - sorry, for some reason I don't seem to be able to link issues to PRs in this repo.
